In [1]:
import pandas as pd

In [6]:
info = {
    "Name" : ["Rahul","Harshite","Shradha"],
    "Age" : [24,53,23],
    "CGPA" : [9.5,7.5,8.5]
}


df = pd.DataFrame(info)

print(df)

       Name  Age  CGPA
0     Rahul   24   9.5
1  Harshite   53   7.5
2   Shradha   23   8.5

In [3]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshite   7.5
2   Shradha   8.5

In [4]:
s = pd.Series([1,2,3,4,5])
s

#index
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
a = pd.Series([24,25,26,27] , index=["Adam","Eve","Bob","Charlie"])
print(a)

Adam       24
Eve        25
Bob        26
Charlie    27
dtype: int64

In [7]:
df = pd.DataFrame([["Adam",23],["Bob",34],["Eve",25]] , columns = ["Name","Age"])
df

   Name  Age
0  Adam   23
1   Bob   34
2   Eve   25

In [8]:
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr,columns=["A","B","C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
#csv data

df = pd.read_csv("employee_data.csv")

print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [11]:
#json data

df = pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [14]:
#Methods

df.head() #starting 5 rows

df.tail()

df.sample()

df.info()

df.shape

df.describe()

df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64